import type { GigListing } from "./gigTypes";

export const MOCK_GIGS: GigListing[] = [
	{
		id: "1",
		hirerName: "Casa Verde Café",
		verified: true,
		location: "Lisbon",
		remoteOk: false,
		postedLabel: "New · 2d",
		isNew: true,
		title: "Hand-painted mural for our terrace launch",
		description:
			"Botanical, sun-washed palette to wrap a 6m garden wall. Bold linework, room to make it yours.",
		budget: "€1,200–1,800",
		duration: "~2 wks",
		tags: ["Mural", "Botanical"],
	},
	{
		id: "2",
		hirerName: "Bordo Records",
		verified: true,
		location: "Remote",
		remoteOk: true,
		postedLabel: "4d ago",
		title: "Album cover & single art illustration series",
		description:
			"A run of five singles ahead of an LP. Moody, editorial illustration that can carry across vinyl and streaming covers.",
		budget: "€800–1,200",
		duration: "3 wks",
		tags: ["Illustration", "Editorial"],
	},
	{
		id: "3",
		hirerName: "Festival Norte",
		verified: true,
		location: "Porto",
		remoteOk: false,
		postedLabel: "New · 1d",
		isNew: true,
		title: "Main-stage backdrop & set pieces",
		description:
			"Large-scale backdrop and modular set pieces for a three-day outdoor festival. Weatherproof materials, bold shapes.",
		budget: "€2,500–3,500",
		duration: "1 month",
		tags: ["Set design", "Large-scale"],
	},
	{
		id: "4",
		hirerName: "Studio Marés",
		verified: false,
		location: "Faro",
		remoteOk: false,
		postedLabel: "New · 3d",
		isNew: true,
		title: "Hand-lettered signage for new bakery",
		description:
			"Warm, hand-lettered window and interior signage for a bakery opening next month. Rustic, approachable tone.",
		budget: "€400–700",
		duration: "~1 wk",
		tags: ["Lettering", "Signage"],
	},
	{
		id: "5",
		hirerName: "Norte Textiles",
		verified: true,
		location: "Remote",
		remoteOk: true,
		postedLabel: "5d ago",
		title: "Botanical print pattern for fabric line",
		description:
			"Repeating botanical pattern for a new summer fabric collection. Deliverable as a seamless vector tile.",
		budget: "€900–1,400",
		duration: "2 wks",
		tags: ["Illustration", "Botanical"],
	},
	{
		id: "6",
		hirerName: "Anfiteatro Municipal",
		verified: false,
		location: "Braga",
		remoteOk: false,
		postedLabel: "New · 4d",
		isNew: true,
		title: "Outdoor mural for amphitheater wall",
		description:
			"A 15m curved wall facing the main plaza. Community-facing piece, weatherproof paint, bold and legible from a distance.",
		budget: "€1,800–2,400",
		duration: "~3 wks",
		tags: ["Mural", "Large-scale"],
	},
];
