import type { Artist } from "./types";

export const MOCK_ARTISTS: Artist[] = [
	{
		id: "1",
		name: "Nadia Okonkwo",
		discipline: "Muralist",
		location: "Lisbon",
		remoteOk: true,
		availabilityLabel: "Free",
		availabilityTone: "available",
		priceTier: "€€",
		tags: ["Botanical"],
		verified: true,
	},
	{
		id: "2",
		name: "Théo Marchand",
		discipline: "Photographer",
		location: "Porto",
		remoteOk: false,
		availabilityLabel: "2 wks",
		availabilityTone: "soon",
		priceTier: "€€€",
		tags: ["Editorial"],
	},
	{
		id: "3",
		name: "Sara Køhler",
		discipline: "Motion designer",
		location: "Remote",
		remoteOk: true,
		availabilityLabel: "Free",
		availabilityTone: "available",
		priceTier: "€€",
		tags: ["3D"],
		verified: true,
	},
	{
		id: "4",
		name: "Yuki Tanaka",
		discipline: "Illustrator",
		location: "Berlin",
		remoteOk: true,
		availabilityLabel: "Free",
		availabilityTone: "available",
		priceTier: "€€",
		tags: ["Lettering"],
	},
	{
		id: "5",
		name: "Omar Haddad",
		discipline: "Muralist",
		location: "Marrakesh",
		remoteOk: false,
		availabilityLabel: "2 wks",
		availabilityTone: "soon",
		priceTier: "€€€",
		tags: ["Large-scale"],
		verified: true,
	},
	{
		id: "6",
		name: "Elena Petrova",
		discipline: "Photographer",
		location: "Remote",
		remoteOk: true,
		availabilityLabel: "Free",
		availabilityTone: "available",
		priceTier: "€€",
		tags: ["Editorial"],
	},
];
