import type { Artist } from "./types";

export const MOCK_ARTISTS: Artist[] = [
	{
		id: "1",
		name: "Nadia Okonkwo",
		discipline: "Muralist",
		location: "Lisbon",
		remoteOk: true,
		availabilityLabel: "Free",
		availabilityTone: "available",
		priceTier: "€€",
		tags: ["Botanical"],
		verified: true,
		bio: "Muralist working in bold botanical linework, mostly on cafés, courtyards, and community walls across Lisbon. Comfortable with large scale and tight timelines.",
	},
	{
		id: "2",
		name: "Théo Marchand",
		discipline: "Photographer",
		location: "Porto",
		remoteOk: false,
		availabilityLabel: "2 wks",
		availabilityTone: "soon",
		priceTier: "€€€",
		tags: ["Editorial"],
		bio: "Editorial photographer with a moody, film-inspired style. Regular contributor to music and culture magazines, available for on-site shoots around Porto.",
	},
	{
		id: "3",
		name: "Sara Køhler",
		discipline: "Motion designer",
		location: "Remote",
		remoteOk: true,
		availabilityLabel: "Free",
		availabilityTone: "available",
		priceTier: "€€",
		tags: ["3D"],
		verified: true,
		bio: "Motion designer blending 3D renders with clean typography for brand launches and social campaigns. Fully remote, quick turnaround on short-form content.",
	},
	{
		id: "4",
		name: "Yuki Tanaka",
		discipline: "Illustrator",
		location: "Berlin",
		remoteOk: true,
		availabilityLabel: "Free",
		availabilityTone: "available",
		priceTier: "€€",
		tags: ["Lettering"],
		bio: "Illustrator and hand-letterer with a soft, editorial touch. Loves packaging and signage work, open to both remote briefs and on-site collaborations.",
	},
	{
		id: "5",
		name: "Omar Haddad",
		discipline: "Muralist",
		location: "Marrakesh",
		remoteOk: false,
		availabilityLabel: "2 wks",
		availabilityTone: "soon",
		priceTier: "€€€",
		tags: ["Large-scale"],
		verified: true,
		bio: "Large-scale muralist known for geometric patterns rooted in North African tilework. Has led community wall projects across Marrakesh and beyond.",
	},
	{
		id: "6",
		name: "Elena Petrova",
		discipline: "Photographer",
		location: "Remote",
		remoteOk: true,
		availabilityLabel: "Free",
		availabilityTone: "available",
		priceTier: "€€",
		tags: ["Editorial"],
		bio: "Editorial and product photographer with a clean, natural-light style. Ships fast, fully remote-friendly workflow with same-week delivery.",
	},
];
